defaults:
  - values:
      layout: "default"

url: "https://ryan.dev.br"
baseurl: ""

timezone: America/Sao_Paulo

plugins:
  - jekyll-polyglot
  - jekyll-sitemap
  - jekyll-seo-tag

languages: ["pt-br", "en"]
default_lang: "pt-br"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

description: Blog pessoal de Ryan Souza, desenvolvedor e estudante na USP, dedicado a artigos sobre engenharia de software e experiências de carreira. Encontre reflexões, dicas e análises sobre desenvolvimento de sistemas, projetos open source e tecnologia. Um espaço para compartilhar conhecimento e insights sobre a indústria de TI.

collections:
  posts:
    output: true
    permalink: /:path/index:output_ext
    name: Posts

exclude:
  - README.md
  - LICENSE

# Google Analytics
google_analytics: G-M3M1CXFGDH

# Google Search Console
google_search_console: HCp1jl4kI2QUPb6FPeGuLeYkceCyGC9jbsiKNk9igqE