defaults:
  - values:
      layout: "default"

url: "https://ryan.dev.br"
baseurl: ""

timezone: America/Sao_Paulo

plugins:
  - jekyll-polyglot

languages: ["pt-br", "en"]
default_lang: ""
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

description: Blog pessoal de Ryan Souza

collections:
  posts:
    output: true
    permalink: /:path/index:output_ext
    name: Posts

exclude:
  - README.md
  - LICENSE
